DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS CHAIR;


CREATE TABLE PLAYER(
    id_player INTEGER AUTO_INCREMENT PRIMARY KEY,
    name_player varchar(100) NOT NULL,
    lastname_player varchar(100) NOT NULL
);

CREATE TABLE COUNTRY(
    player INTEGER  REFERENCES player(id_player),
    name varchar(100) NOT NULL
);
CREATE TABLE DEPARTMENT (
  ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  NAME varchar(100) NOT NULL
);

CREATE TABLE CHAIR (
  DEPARTMENT INTEGER REFERENCES DEPARTMENT(ID),
  NAME varchar(100) DEFAULT NULL
);
--CREATE TABLE DEPARTMENT (
--  ID_DEPARTMENT INTEGER AUTO_INCREMENT PRIMARY KEY,
 -- NAME varchar(100) NOT NULL
--);

--CREATE TABLE CHAIR (
--  ID_CHAR INTEGER AUTO_INCREMENT PRIMARY KEY,
--  NAME varchar(100) DEFAULT NULL,
 -- ID_DEPARTMENT INTEGER NOT NULL
--);
--ALTER TABLE CHAIR
--ADD FOREIGN KEY (ID_DEPARTMENT)
--REFERENCES DEPARTMENT(ID_DEPARTMENT);